name: Send Email on Commit

on:
  push:
    branches:
      - main  # Substitua pelo nome da sua branch principal

jobs:
  send-email:
    runs-on: ubuntu-latest

    container:
      image: python:3.9  # Imagem Docker com Python 3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script to send email
        run: python send_email.py  # Substitua pelo nome do seu arquivo Python

      - name: Cleanup
        run: |
          rm -rf ~/.cache/pip

